### PR TITLE
Removed duplicate color

### PR DESCRIPTION
**Pull request by welnanick**
I changed lightBlack from #586e75 to #002b36 to match what altercation/vim-colors-solarized (the official vim theme) expects it to be.

### CODE REVIEW

**Comment by lewisflude** [comment]
@ghosh Is there any chance we can get this merged in?

**Comment by sebkolind** [comment]
This should be merged.

**Comment by estebanrao** [comment]
@ghosh can this be merged? Thanks

**Comment by sukima** [comment]
Why is this not merged yet?

**Comment by ghosh** [comment]
Sorry folks. Was burnt out for a while. 🙏 Thanks for the constant reminders.

**Comment by lewisflude** [comment]
It’s all good! Important to look after yourself! Thanks for merging :)

**Pull request merged**
